import './global.css';

import { Lora } from 'next/font/google';
import { ClientProviders } from './providers';
import { Toaster } from 'react-hot-toast';

const lora = Lora({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // choose the weights you need
  variable: '--font-lora', // CSS variable
});

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={lora.variable}>
      <body>
        <ClientProviders>
          {children}
           <Toaster
        position="top-center"
        toastOptions={{
          duration: 3000,
        }}
      />
        </ClientProviders>
      </body>
    </html>
  );
}
