name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies (only for backend app if package.json exists there)
      - run: npm ci --legacy-peer-deps

      # Setup env vars from GitHub Secrets
      - name: Setup environment
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      # Lint backend
      - run: npx nx run backend:lint

      # Run tests (Jest/Vitest)
      - run: npx nx run backend:test

      # Type checking
      - run: npx nx run backend:typecheck

      # Build backend
      - run: npx nx run backend:build